# -*- coding: utf-8 -*-
"""Labphase - Phase 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18wET-VnRxCKsXfpJaYbDb0tbHtOeDcgV

###**1- Comprendre l'objectif de chaque technique (Théorie)**

Tokenisation: Diviser un texte brut en unités plus petites (mots ou phrases) appelées "tokens".

Mots Stop (Stop words):	Supprimer les mots fréquents qui n'apportent pas de valeur sémantique (ex: "le", "et", "de").

Tagging (POS Tagging):	Identifier la fonction grammaticale de chaque mot (nom, verbe, adjectif).

Stemming (Racinisation):	Réduire un mot à sa racine de manière brutale (ex: "cherchons" -> "cherch").

Lemmatisation	Réduire: un mot à sa forme canonique (dictionnaire) en tenant compte du contexte (ex: "sommes" -> "être").

###**Implémentation de  chaque technique en utilisant Python et NLTK**
"""

!pip install nltk

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

# Téléchargement des ressources NLTK
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

# 1. Préparation des outils pour le français
stemmer = SnowballStemmer('french')
stop_words = set(stopwords.words('french'))

# 1. Liste des phrases (Catégorie: Support technique)
phrases = [
    "Mon ordinateur ne s'allume plus et j'ai un écran noir.",
    "Mon clavier ne répond plus quand je tape sur les touches.",
    "L'application se ferme toute seule dès que je j'essaie de l'ouvrir.",
    "J'ai un message d'erreur bleu qui s'affiche au démarrage du système.",
    "Ma connexion internet est très lente et se coupe sans arrêt.",
    "Le logiciel refuse de s'installer car il manque un fichier système."
]

print(f"{'PHRASE ORIGINALE':<70} | {'STEMS (RACINES)'}")
print("-" * 110)

for texte in phrases:
    # 2. Tokenisation
    tokens = word_tokenize(texte, language='french')

    # 3. Suppression des mots stop et ponctuation (Stop words))
    tokens_filtres = [mot for mot in tokens if mot.lower().isalpha() and mot.lower() not in stop_words]

    # 4. Stemming (Racinisation)
    stems = [stemmer.stem(mot) for mot in tokens_filtres]

    # Affichage des résultats
    print(f"{texte:<70} | {stems}")

"""### **Évaluation des performances**

L'analyse des stems (racines) obtenus montre des points forts et quelques points de vigilance pour la classification :

**Points Forts (Succès de la classification)**
Des racines comme ordin, clavi, internet, logiciel, et system sont très marquées. Si ces mots apparaissent, le chatbot aura une probabilité très élevée de classer correctement la requête en « Support technique ».

La phrase sur le logiciel passe de 12 mots à 6 racines utiles. On a éliminé le "bruit" (le, de, il, un).

On remarque que "système" est devenu system. Cela permettra de faire correspondre "système" et "systèmes" (pluriel) à la même catégorie.

**Points de Vigilance (Limites du Stemming/Stop-words)**
Reste de mots fonctionnels : Des mots comme plus, quand, tout, des, tres, san, car sont restés après le filtrage.
Ces mots sont "neutres" et n'aident pas à distinguer le support de la facturation.

On pourrait enrichir la liste des stop_words avec ces termes pour ne garder que le contenu technique pur.

Dans la phrase 3, le mot "j'essaie" a disparu ou a été mal traité (on ne voit pas la racine essai). Cela arrive souvent quand la tokenisation sépare mal l'apostrophe en français.

Perte de sens (Phrase 3) : Le résultat ['ferm', 'tout', 'seul', 'des'] est un peu faible. Il manque le mot "application".
"""