# -*- coding: utf-8 -*-
"""Labphase - phase 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Enx1fka1NNSw2S_0CjI2oDVCMSretCu5
"""

!pip install nltk

"""####**1. Comprendre la différence entre Naïve Bayes et l'Arbre de Décision**

Bien que les classificateurs Naïve Bayes et les Arbres de Décision soient tous deux utilisés pour la classification de texte, ils reposent sur des fondements logiques et mathématiques radicalement différents.

Le classificateur Naïve Bayes est basé sur une approche probabiliste issue du théorème de Bayes. Dans le contexte du traitement du langage naturel, il calcule la probabilité qu'une phrase appartienne à une catégorie donnée (comme « support technique ») en fonction des mots qu'elle contient. Il est qualifié de « naïf » car il fait l'hypothèse simplificatrice que chaque mot est indépendant des autres. Par exemple, il traitera les mots "écran" et "noir" comme deux preuves séparées sans tenir compte de leur relation directe. Malgré cette simplification, il est extrêmement performant pour le texte car il gère très bien les grands volumes de vocabulaire et reste stable même avec un petit ensemble de données d'entraînement.

L'Arbre de Décision, à l'inverse, adopte une approche logique et hiérarchique. Au lieu de calculer des probabilités globales, il construit une suite de tests successifs sous forme de nœuds. On peut l'imaginer comme un jeu de questions-réponses : « Est-ce que le mot 'facture' est présent ? Si oui, descendre à gauche vers la catégorie Facturation ; si non, vérifier si le mot 'écran' est présent ». Chaque branche de l'arbre mène à une décision finale. Sa grande force réside dans sa lisibilité, car un humain peut facilement suivre le cheminement qui a mené à la classification. Cependant, il a tendance à être plus sensible au bruit et peut facilement faire du « sur-apprentissage » (overfitting), c'est-à-dire apprendre par cœur les phrases d'entraînement plutôt que de généraliser les concepts.

En résumé, la différence fondamentale tient dans la méthode de décision : Naïve Bayes additionne des poids de probabilité sur l'ensemble de la phrase, tandis que l'Arbre de Décision cherche des mots discriminants spécifiques pour valider des conditions logiques. Pour un chatbot, Naïve Bayes est souvent préféré pour sa robustesse face aux variations de langage, tandis que l'Arbre de Décision est utile lorsque l'on veut comprendre précisément quelles règles déclenchent quelle réponse.
"""

import pandas as pd
import nltk
import random
from nltk.tokenize import word_tokenize
from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords
from nltk import classify

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

# 1. Configuration des outils NLTK
stemmer = SnowballStemmer('french')
stop_words = set(stopwords.words('french'))

# 2. Chargement du dataset de 1500 messages
# On utilise messages_support_clients_france.csv qui contient les colonnes 'Catégorie' et 'Message'
df = pd.read_csv("/content/messages_support_clients_france.csv", sep=None, engine='python', encoding='utf-8-sig')

# 3. Fonction d'extraction des racines (Features)
def extraire_features(phrase):
    if not isinstance(phrase, str): return {}
    # Tokenisation et passage en minuscule
    tokens = word_tokenize(phrase.lower(), language='french')
    # Filtrage (mots vides + ponctuation) et Stemming
    stems = [stemmer.stem(m) for m in tokens if m.isalpha() and m not in stop_words]
    # Retourne le dictionnaire au format NLTK {racine: True}
    return {mot: True for mot in stems}

# 4. Construction du dataset pour l'entraînement
# On associe chaque message à sa catégorie réelle du fichier CSV
dataset_complet = []
for index, row in df.iterrows():
    features = extraire_features(row['Message'])
    label = row['Catégorie']
    dataset_complet.append((features, label))

# 5. Division Automatique (Évaluation par Split 80/20)
random.seed(42) # Garantit que les résultats sont les mêmes à chaque exécution
random.shuffle(dataset_complet)

taille_split = int(len(dataset_complet) * 0.8)
train_set = dataset_complet[:taille_split]
test_set = dataset_complet[taille_split:]

# 6. Entraînement des deux modèles
print("Entraînement en cours sur 1500 messages...")
nb_model = nltk.NaiveBayesClassifier.train(train_set)
dt_model = nltk.DecisionTreeClassifier.train(train_set)

# 7. Évaluation des performances
accuracy_nb = classify.accuracy(nb_model, test_set)
accuracy_dt = classify.accuracy(dt_model, test_set)

# 8. Affichage du rapport final de la Phase 2
print("\n" + "="*40)
print("RAPPORT DE PERFORMANCE - PHASE 2")
print("="*40)
print(f"Dataset utilisé : messages_support_clients_france.csv")
print(f"Taille de l'échantillon de test : {len(test_set)} messages")
print(f"Précision Naive Bayes      : {accuracy_nb:.2%}")
print(f"Précision Arbre de Décision : {accuracy_dt:.2%}")
print("="*40)

# Affichage des mots les plus informatifs (pour Naive Bayes)
nb_model.show_most_informative_features(10)



"""#**Exploration des moyens d’améliorer la précision des classificateurs**

**Performance initiale**: Les modèles atteignent une précision robuste de 91,33%, validant ainsi l'efficacité du prétraitement NLTK.

**Limites des unigrammes :** L'analyse actuelle par mot unique ignore les nuances comme "non reçu" ou "sans frais".

**Apport des bigrammes :** L'intégration de paires de mots permettra de capturer le contexte local et de lever les ambiguïtés.

**Pondération TF-IDF :** Cette technique valorisera les termes rares et techniques au détriment des mots trop fréquents.

**Rôle des hyperparamètres :** Leur optimisation fine est cruciale pour adapter la structure du modèle à la complexité des messages.

**Contrôle de l'Arbre de Décision :** Régler la profondeur maximale empêchera le modèle d'apprendre par cœur les erreurs de frappe.

**Généralisation :** Ce réglage force l'arbre à ne conserver que les nœuds de décision les plus discriminants et universels.

**Stabilité via Naive Bayes :** L'ajustement du lissage de Laplace garantit une probabilité non nulle pour les nouveaux mots clients.

**Gestion de l'imprévu :** Ces corrections permettent au chatbot de rester fonctionnel face au vocabulaire jamais rencontré en entraînement.

Ces optimisations visent à stabiliser la classification pour dépasser les 95% de fiabilité en production.
"""